-- RETIRED 2026-10-07 - this demo seed/cleanup script was removed on purpose.
-- Production is live: the demo vehicles/auctions/bids were copied to the
-- public.recovery_20261007_* tables and are deleted by the hand-run
-- supabase/manual/20261007_delete_demo_content.sql. Do not re-seed demo content.
-- The original script is in git history (git show 7be02cf:<this path>).
