"use client";

// Forgot-password request page. Emails a recovery link that lands on
// /reset-password/callback. The same page also handles links generated by the
// mobile apps (their redirectTo points here), so password reset works for all
// three apps from one web flow.

import { useState } from "react";
import Link from "next/link";
import { MailCheck } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createClient } from "@/lib/supabase/client";
import { useTranslations } from "@/i18n/provider";

export default function ResetPasswordPage() {
  const t = useTranslations("auth");
  const [email, setEmail] = useState("");
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim()) return;
    setLoading(true);
    setError(null);
    const supabase = createClient();
    const redirectTo = `${window.location.origin}/reset-password/callback`;
    const { error } = await supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo });
    setLoading(false);
    // Always show the same confirmation (don't reveal whether an account exists).
    if (error && !/rate limit/i.test(error.message)) {
      // surface only hard failures; otherwise show the neutral "sent" state
      setSent(true);
      return;
    }
    setSent(true);
  };

  return (
    <div className="rounded-2xl border border-grey-200 bg-white p-8 shadow-sm">
      {sent ? (
        <div className="text-center">
          <span className="mx-auto mb-4 grid size-12 place-items-center rounded-full bg-success-50 text-success-600 ring-1 ring-success-100">
            <MailCheck className="size-6" />
          </span>
          <h1 className="text-2xl font-extrabold text-grey-900">{t("resetSentTitle")}</h1>
          <p className="mt-2 text-sm text-grey-600">{t("resetSentBody")}</p>
          <Link href="/login" className="mt-6 inline-block text-sm font-semibold text-brand-700 hover:underline">
            {t("backToLogin")}
          </Link>
        </div>
      ) : (
        <>
          <header className="mb-7 text-center">
            <h1 className="text-2xl font-extrabold text-grey-900">{t("resetTitle")}</h1>
            <p className="mt-2 text-sm text-grey-600">{t("resetSubtitle")}</p>
          </header>
          <form onSubmit={submit} className="space-y-5">
            <div className="space-y-1.5">
              <Label htmlFor="email">{t("email")}</Label>
              <Input
                id="email" type="email" required autoComplete="email"
                value={email} onChange={(e) => setEmail(e.target.value)}
                placeholder="you@company.com" className="h-11"
              />
            </div>
            {error && <p className="rounded-md bg-error-50 px-3 py-2 text-sm text-error-700">{error}</p>}
            <Button type="submit" size="lg" disabled={loading} className="h-11 w-full text-base">
              {loading ? "…" : t("sendResetLink")}
            </Button>
          </form>
          <p className="mt-6 text-center text-sm text-grey-600">
            <Link href="/login" className="font-semibold text-brand-700 hover:underline">{t("backToLogin")}</Link>
          </p>
        </>
      )}
    </div>
  );
}
